### ISSUE TITLE
Create signup page

### ISSUE THREAD

**Issue by prestonButton** [prestonButton/DiceGame#1]
Keep styles similar to the homepage - can take the background gradient straight from there. It should have a form that takes username and email and sends that to the database - would be a good pair to build with the login page

**Comment by shahbaazkyz** [comment]
Working on it.

**Comment by prestonButton** [comment]
> Working on it.


Please create a new branch and pull request - create a component in the components folder for the auth form - only needs username and password. The login one should be called login and the submit button should have the text "Login". The Sign up should be called 'Sign Up' and the submit button should have the text 'Sign Up'. Pass this in as a prop to the form. Create the JSX, and I will hook in the backend when I have it completed

**Comment by sreehari212000** [comment]
Hey can you assign me this?

**Comment by prestonButton** [comment]
I did

**Comment by sreehari212000** [comment]
![preston](https://user-images.githubusercontent.com/108830784/231388282-fd2a7c00-86ee-4a22-b370-5fdee9be6381.png)
Are you expecting something like this?

**Comment by prestonButton** [comment]
That is great. Just change the text to white and model the button after the
buttons on the homepage

**Comment by sreehari212000** [comment]
Sure, Button should be like the button on homepage right?

**Comment by prestonButton** [comment]
Yes
